### ISSUE TITLE
数据很少能跑吗？

### ISSUE THREAD

**Issue by laojifeima** [lemonhu/BERT-NER-pytorch#1]
博主你好，我最近也在使用bert，遇到了问题。我一个实验使用训练集有超百万字的规模，但是使用另一个只有几万字的训练集（ccks）时不能识别出一个实体。请问使用bert时，我遇到的问题时训练集规模吗？

**Comment by lemonhu** [comment]
根据描述，我不太清楚你的NER训练集的数量级，我采用的标准数据集MSRA训练集有42000条，可以参考一下。

**Comment by laojifeima** [comment]
谢谢博主。我就只有600句，以字做的。

**Comment by lemonhu** [comment]
个人经验来看，这个数量集NER训练可能会发生欠拟合，需要增加训练集。

**Comment by laojifeima** [comment]
但是同样的数据集我不加bert能拟合，p,r,f都能有70+。加了bert一个实体识别不出来，是bert的原因吗？

**Comment by lemonhu** [comment]
这个应该不是Bert模型的原因。
